import type { AppData } from "./types"

export const initialData: AppData = {
  characters: [
    // ===== 星3 キャラクター（12体）=====
    {
      id: "c_s3_endou",
      name: "円堂守",
      position: "GK",
      attribute: "山",
      rarity: "星3",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "c_s3_kazamaru",
      name: "風丸一郎太",
      position: "DF",
      attribute: "風",
      rarity: "星3",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "c_s3_kabeyama",
      name: "壁山塀吾郎",
      position: "DF",
      attribute: "山",
      rarity: "星3",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "スキル詳細・チーム要確認",
      verificationStatus: "要検証",
    },
    {
      id: "c_s3_kidou",
      name: "鬼道有人",
      position: "MF",
      attribute: "風",
      rarity: "星3",
      team: "帝国学園",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "チーム要確認",
      verificationStatus: "要検証",
    },
    {
      id: "c_s3_fudo",
      name: "不動明王",
      position: "MF",
      attribute: "火",
      rarity: "星3",
      team: "イナズマジャパン",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "c_s3_someoka",
      name: "染岡竜吾",
      position: "FW",
      attribute: "林",
      rarity: "星3",
      team: "イナズマジャパン",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "チーム要確認",
      verificationStatus: "要検証",
    },
    {
      id: "c_s3_tategami",
      name: "立向居勇気",
      position: "GK",
      attribute: "林",
      rarity: "星3",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "スキル詳細要確認",
      verificationStatus: "要検証",
    },
    {
      id: "c_s3_gouenji",
      name: "豪炎寺修也",
      position: "FW",
      attribute: "火",
      rarity: "星3",
      team: "イナズマジャパン",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "c_s3_fubuki",
      name: "吹雪士郎",
      position: "FW",
      attribute: "風",
      rarity: "星3",
      team: "イナズマジャパン",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "c_s3_hiroto",
      name: "基山ヒロト",
      position: "FW",
      attribute: "火",
      rarity: "星3",
      team: "",
      series: "イナズマイレブン2",
      obtainMethod: "ガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "所属チーム不明・要確認",
      verificationStatus: "要検証",
    },
    {
      id: "c_s3_endou_jpn2026",
      name: "円堂守（日本代表2026）",
      position: "MF",
      attribute: "山",
      rarity: "星3",
      team: "日本代表",
      series: "コラボ",
      obtainMethod: "コラボガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "コラボキャラ・詳細要確認",
      verificationStatus: "要検証",
    },
    {
      id: "c_s3_kidou_jpn2026",
      name: "鬼道有人（日本代表2026）",
      position: "MF",
      attribute: "風",
      rarity: "星3",
      team: "日本代表",
      series: "コラボ",
      obtainMethod: "コラボガチャ",
      isGachaLimited: true,
      initialAwakeningRank: "growing player",
      currentAwakeningRank: "growing player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "コラボキャラ・詳細要確認",
      verificationStatus: "要検証",
    },

    // ===== 星2 キャラクター（13体）=====
    {
      id: "c_s2_sakuma",
      name: "佐久間次郎",
      position: "FW",
      attribute: "林",
      rarity: "星2",
      team: "帝国学園",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_someoka",
      name: "染岡竜吾",
      position: "FW",
      attribute: "林",
      rarity: "星2",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_yamino",
      name: "闇野カゲト",
      position: "FW",
      attribute: "林",
      rarity: "星2",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_kidou",
      name: "鬼道有人",
      position: "MF",
      attribute: "風",
      rarity: "星2",
      team: "帝国学園",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_ichinose",
      name: "一之瀬一哉",
      position: "MF",
      attribute: "林",
      rarity: "星2",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_kogure",
      name: "木暮夕弥",
      position: "DF",
      attribute: "林",
      rarity: "星2",
      team: "イナズマジャパン",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_kurimatsu",
      name: "栗松鉄平",
      position: "DF",
      attribute: "火",
      rarity: "星2",
      team: "イナズマジャパン",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_tsunakai",
      name: "綱海条介",
      position: "DF",
      attribute: "風",
      rarity: "星2",
      team: "イナズマジャパン",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_takaiya",
      name: "飛鷹征矢",
      position: "DF",
      attribute: "風",
      rarity: "星2",
      team: "イナズマジャパン",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_domon",
      name: "土門飛鳥",
      position: "DF",
      attribute: "林",
      rarity: "星2",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_kazamaru",
      name: "風丸一郎太",
      position: "DF",
      attribute: "風",
      rarity: "星2",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_genda",
      name: "源田幸次郎",
      position: "GK",
      attribute: "火",
      rarity: "星2",
      team: "帝国学園",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s2_endou",
      name: "円堂守",
      position: "GK",
      attribute: "山",
      rarity: "星2",
      team: "雷門中",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player+",
      currentAwakeningRank: "normal player+",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },

    // ===== 星1 キャラクター（16体）=====
    {
      id: "c_s1_kisaragi",
      name: "如月まこ",
      position: "FW",
      attribute: "林",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_matsuno",
      name: "松野空介",
      position: "FW",
      attribute: "風",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_megane",
      name: "目金欠流",
      position: "FW",
      attribute: "林",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_handa",
      name: "半田真一",
      position: "MF",
      attribute: "風",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_sakiyama",
      name: "咲山修二",
      position: "MF",
      attribute: "火",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_shishido",
      name: "宍戸佐吉",
      position: "MF",
      attribute: "火",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_shorinji",
      name: "少林寺歩",
      position: "MF",
      attribute: "林",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_narugami",
      name: "成神健也",
      position: "MF",
      attribute: "風",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_doumen",
      name: "洞面秀一郎",
      position: "MF",
      attribute: "風",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_henmi",
      name: "辺見渡",
      position: "MF",
      attribute: "風",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_manjo",
      name: "万丈一道",
      position: "DF",
      attribute: "林",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_gojo",
      name: "五条勝",
      position: "DF",
      attribute: "林",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_kabeyama",
      name: "壁山塀吾郎",
      position: "DF",
      attribute: "林",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_ono",
      name: "大野伝助",
      position: "DF",
      attribute: "山",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_kageno",
      name: "影野仁",
      position: "DF",
      attribute: "林",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
    {
      id: "c_s1_kurimatsu",
      name: "栗松鉄平",
      position: "DF",
      attribute: "火",
      rarity: "星1",
      team: "",
      series: "イナズマイレブン",
      obtainMethod: "ガチャ",
      isGachaLimited: false,
      initialAwakeningRank: "normal player",
      currentAwakeningRank: "normal player",
      maxAwakeningRank: "legendary player+",
      isOwned: false,
      isFavorite: false,
      memo: "",
      verificationStatus: "要検証",
    },
  ],

  passiveSkills: [
    // ===== 豪炎寺修也（5スキル・非公式確認済み）=====
    {
      id: "ps_gouenji_kick1",
      name: "キック+",
      description: "自身のキックを1344上昇",
      activationCondition: "常時（Lv1）",
      effectType: "ステータス強化",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inazuma-cross/80072293",
    },
    {
      id: "ps_gouenji_tp",
      name: "最大TP+",
      description: "自身の最大TPを30上昇",
      activationCondition: "常時（覚醒2回目）",
      effectType: "TP強化",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inazuma-cross/80072293",
    },
    {
      id: "ps_gouenji_score",
      name: "【自得点/累】雷門・イナズマジャパン+",
      description: "自身がゴールを入れるたびに全パラメータを199上昇",
      activationCondition: "得点時（累積）・雷門またはイナズマジャパンタグが3人以上（覚醒3回目）",
      effectType: "累積バフ",
      targetTeam: "雷門/イナズマジャパン",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inazuma-cross/80072293",
    },
    {
      id: "ps_gouenji_kessoku",
      name: "【結束】キック+",
      description: "自身のキックを2194上昇",
      activationCondition: "雷門またはイナズマジャパンタグの味方が3人以上（常時）",
      effectType: "チームタグ条件バフ",
      targetTeam: "雷門/イナズマジャパン",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inazuma-cross/80072293",
    },
    {
      id: "ps_gouenji_shoot",
      name: "【決定機】シュートパワー+",
      description: "自身のシュート技の威力を99上昇",
      activationCondition: "ペナルティエリア内でシュート時（Lv41）",
      effectType: "必殺技強化",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inazuma-cross/80072293",
    },
    // ===== 吹雪士郎（5スキル・非公式確認済み）=====
    {
      id: "ps_fubuki_tp",
      name: "最大TP+",
      description: "自身の最大TPを30上昇",
      activationCondition: "常時（覚醒2回目）",
      effectType: "TP強化",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inakuro-cross/80072362",
    },
    {
      id: "ps_fubuki_wolf",
      name: "ウルフレジェンドパワー+改",
      description: "ウルフレジェンドの威力を35上昇・射程を10上昇",
      activationCondition: "常時（覚醒3回目）",
      effectType: "必殺技強化",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inakuro-cross/80072362",
    },
    {
      id: "ps_fubuki_kessoku",
      name: "【結束】キック+",
      description: "自身のキックを2240上昇",
      activationCondition: "イナズマジャパンタグの味方が3人以上（常時）",
      effectType: "チームタグ条件バフ",
      targetTeam: "イナズマジャパン",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inakuro-cross/80072362",
    },
    {
      id: "ps_fubuki_kick",
      name: "キック+",
      description: "自身のキックを1344上昇",
      activationCondition: "常時（Lv11）",
      effectType: "ステータス強化",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inakuro-cross/80072362",
    },
    {
      id: "ps_fubuki_crt",
      name: "パワー&CRT",
      description: "自身の風属性技の威力を36上昇・クリティカル率を10%上昇",
      activationCondition: "常時（風属性技使用時・Lv41）",
      effectType: "必殺技強化",
      targetAttribute: "風",
      verificationStatus: "非公式確認済み",
      sourceUrl: "https://appmedia.jp/inakuro-cross/80072362",
    },
    // ===== 不動明王（5スキル・非公式確認済み）=====
    {
      id: "ps_fudo_tech1",
      name: "テクニック+",
      description: "自身のテクニックを215上昇",
      activationCondition: "常時（Lv1）",
      effectType: "ステータス強化",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "ps_fudo_tech2",
      name: "テクニック+",
      description: "自身のテクニックを67上昇",
      activationCondition: "常時（Lv11）",
      effectType: "ステータス強化",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "ps_fudo_tp",
      name: "最大TP+",
      description: "自身の最大TPを30上昇",
      activationCondition: "常時（覚醒2回目）",
      effectType: "TP強化",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "ps_fudo_tech_foul",
      name: "テクニック+/チームファウル率減少",
      description: "自身のテクニックを266上昇・味方のファウル率を1%減少",
      activationCondition: "常時（覚醒3回目）",
      effectType: "ステータス強化/チームサポート",
      verificationStatus: "非公式確認済み",
    },
    {
      id: "ps_fudo_dribble",
      name: "【結束】ドリブルパワー+",
      description: "自身のドリブル技の威力を18上昇",
      activationCondition: "イナズマジャパンタグの味方が3人以上（Lv41）",
      effectType: "必殺技強化",
      targetTeam: "イナズマジャパン",
      verificationStatus: "非公式確認済み",
    },
    // ===== 円堂守（要検証）=====
    {
      id: "ps_endou_catch1",
      name: "キャッチ+",
      description: "自身のキャッチを上昇",
      activationCondition: "常時",
      effectType: "ステータス強化",
      verificationStatus: "要検証",
    },
    {
      id: "ps_endou_kessoku",
      name: "【結束】守備力+",
      description: "雷門タグの味方が3人以上いる場合・自身の守備力を上昇",
      activationCondition: "雷門タグの味方が3人以上",
      effectType: "チームタグ条件バフ",
      targetTeam: "雷門",
      verificationStatus: "要検証",
    },
  ],

  characterPassiveSkills: [
    // 豪炎寺修也（星3）
    { id: "cps_gouenji_1", characterId: "c_s3_gouenji", passiveSkillId: "ps_gouenji_kick1" },
    { id: "cps_gouenji_2", characterId: "c_s3_gouenji", passiveSkillId: "ps_gouenji_tp" },
    { id: "cps_gouenji_3", characterId: "c_s3_gouenji", passiveSkillId: "ps_gouenji_score" },
    { id: "cps_gouenji_4", characterId: "c_s3_gouenji", passiveSkillId: "ps_gouenji_kessoku" },
    { id: "cps_gouenji_5", characterId: "c_s3_gouenji", passiveSkillId: "ps_gouenji_shoot" },
    // 吹雪士郎（星3）
    { id: "cps_fubuki_1", characterId: "c_s3_fubuki", passiveSkillId: "ps_fubuki_tp" },
    { id: "cps_fubuki_2", characterId: "c_s3_fubuki", passiveSkillId: "ps_fubuki_wolf" },
    { id: "cps_fubuki_3", characterId: "c_s3_fubuki", passiveSkillId: "ps_fubuki_kessoku" },
    { id: "cps_fubuki_4", characterId: "c_s3_fubuki", passiveSkillId: "ps_fubuki_kick" },
    { id: "cps_fubuki_5", characterId: "c_s3_fubuki", passiveSkillId: "ps_fubuki_crt" },
    // 不動明王（星3）
    { id: "cps_fudo_1", characterId: "c_s3_fudo", passiveSkillId: "ps_fudo_tech1" },
    { id: "cps_fudo_2", characterId: "c_s3_fudo", passiveSkillId: "ps_fudo_tech2" },
    { id: "cps_fudo_3", characterId: "c_s3_fudo", passiveSkillId: "ps_fudo_tp" },
    { id: "cps_fudo_4", characterId: "c_s3_fudo", passiveSkillId: "ps_fudo_tech_foul" },
    { id: "cps_fudo_5", characterId: "c_s3_fudo", passiveSkillId: "ps_fudo_dribble" },
    // 円堂守（星3）
    { id: "cps_endou_1", characterId: "c_s3_endou", passiveSkillId: "ps_endou_catch1" },
    { id: "cps_endou_2", characterId: "c_s3_endou", passiveSkillId: "ps_endou_kessoku" },
  ],

  materials: [
    // ===== 属性石（4種）=====
    {
      id: "mat_stone_fire",
      name: "火の属性石",
      materialType: "属性石",
      attribute: "火",
      ownedCount: 0,
      obtainMethod: "ガチャ・人脈ボード・交換所",
    },
    {
      id: "mat_stone_wind",
      name: "風の属性石",
      materialType: "属性石",
      attribute: "風",
      ownedCount: 0,
      obtainMethod: "ガチャ・人脈ボード・交換所",
    },
    {
      id: "mat_stone_mountain",
      name: "山の属性石",
      materialType: "属性石",
      attribute: "山",
      ownedCount: 0,
      obtainMethod: "ガチャ・人脈ボード・交換所",
    },
    {
      id: "mat_stone_forest",
      name: "林の属性石",
      materialType: "属性石",
      attribute: "林",
      ownedCount: 0,
      obtainMethod: "ガチャ・人脈ボード・交換所",
    },
    // ===== 覚醒魂（星3 ユニーク12体）=====
    // 同名キャラが複数レアリティに存在する場合は覚醒魂を共有（円堂守・鬼道有人・風丸・染岡・壁山）
    {
      id: "mat_soul_endou",
      name: "円堂守の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り・交換所（試練のコイン2000）",
    },
    {
      id: "mat_soul_kazamaru",
      name: "風丸一郎太の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_kabeyama",
      name: "壁山塀吾郎の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_kidou",
      name: "鬼道有人の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_fudo",
      name: "不動明王の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_someoka",
      name: "染岡竜吾の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_tategami",
      name: "立向居勇気の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_gouenji",
      name: "豪炎寺修也の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り・人脈ボード・交換所（試練のコイン2000）",
    },
    {
      id: "mat_soul_fubuki",
      name: "吹雪士郎の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_hiroto",
      name: "基山ヒロトの覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_endou_jpn2026",
      name: "円堂守（日本代表2026）の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "コラボガチャ被り",
    },
    {
      id: "mat_soul_kidou_jpn2026",
      name: "鬼道有人（日本代表2026）の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "コラボガチャ被り",
    },
    // ===== 覚醒魂（星2固有 9体）=====
    {
      id: "mat_soul_sakuma",
      name: "佐久間次郎の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_yamino",
      name: "闇野カゲトの覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_ichinose",
      name: "一之瀬一哉の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_kogure",
      name: "木暮夕弥の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_kurimatsu",
      name: "栗松鉄平の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_tsunakai",
      name: "綱海条介の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_takaiya",
      name: "飛鷹征矢の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_domon",
      name: "土門飛鳥の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_genda",
      name: "源田幸次郎の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    // ===== 覚醒魂（星1固有 14体）=====
    {
      id: "mat_soul_kisaragi",
      name: "如月まこの覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_matsuno",
      name: "松野空介の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_megane",
      name: "目金欠流の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_handa",
      name: "半田真一の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_sakiyama",
      name: "咲山修二の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_shishido",
      name: "宍戸佐吉の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_shorinji",
      name: "少林寺歩の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_narugami",
      name: "成神健也の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_doumen",
      name: "洞面秀一郎の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_henmi",
      name: "辺見渡の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_manjo",
      name: "万丈一道の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_gojo",
      name: "五条勝の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_ono",
      name: "大野伝助の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
    {
      id: "mat_soul_kageno",
      name: "影野仁の覚醒魂",
      materialType: "覚醒魂",
      ownedCount: 0,
      obtainMethod: "ガチャ被り",
    },
  ],
}
